### ISSUE TITLE
QUESTION: differences between this and jswanner/private_attr

### ISSUE THREAD

**Issue by oehlschl** [wzcolon/private_attrs#1]
Not an issue so much as a comment that I think would help this library. I'm also interested in introducing this pattern, and it looks like there's an older (and possibly unmaintained) implementation at https://github.com/jswanner/private_attr .

Are there any features this library provides that `private_attr` does not (or vice versa)? It might help to at least disambiguate between the two in the README, as anyone who finds this repo organically will have likely stumbled across the other as well.

Thanks!

**Comment by wzcolon** [comment]
@oehlschl Sorry for the slow response. I was unaware of the existing library when I put this together. It looks like that library also includes methods for protected attrs as well.

**Comment by oehlschl** [comment]
@wzcolon Understood! Thanks for following up.
